.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-DIFF\-ANSIBLE\-VAULT" "1" "August 2016" "" ""
.
.SH "NAME"
\fBgit\-diff\-ansible\-vault\fR \- Diff ansible vault encrypted files in git history
.
.SH "SYNOPSIS"
git diff\-ansible\-vault [\-r \fIrevision\fR] \fI\-p \fIpath\fR\fR
.
.P
\fIrevision\fR is the git revision to diff\. \fIpath\fR is the file system path to scope the diff to\.
.
.SH "DESCRIPTION"
Running \fBgit diff\fR on files encrypted with ansible vault results in some pretty unhelpful output\.
.
.P
\fBgit diff\-ansible\-vault\fR is custom git command that detects files encrypted with ansible vault within the diff, and safely decrypts them to reveal the true changes\.
.
.SH "EXAMPLES"
.
.nf

$ git diff\-ansible\-vault

$ git diff\-ansible\-vault \-r master\.\.some\-branch \-p path/to/dir

$ git diff\-ansible\-vault \-\-vault\-password\-file \.vaultpass
.
.fi
.
.SH "OPTIONS"
.
.TP
\fB\-r\fR, \fB\-\-revision <revision>\fR
Show diff for git revision, e\.g\. master\.\.some\-branch
.
.TP
\fB\-p\fR, \fB\-\-path <path>\fR
Restrict diff to path, e\.g\. support/config\.yml
.
.TP
\fB\-\-cached\fR, \fB\-\-staged\fR
Show diff for staged changes
.
.TP
\fB\-\-no\-pager\fR
Do not pipe output into a pager
.
.TP
\fB\-\-vault\-password\-file <path>\fR
Vault password file path, defaults to \.vault\-pass
.
.TP
\fB\-\-vault\-only\fR
Restrict diff to vault files only
.
.TP
\fB\-\-color\fR, \fB\-\-colour\fR
Turn on coloured output
.
.TP
\fB\-\-no\-color\fR, \fB\-\-no\-colour\fR
Turn off coloured diff
.
.TP
\fB\-\-verbose\fR
Display verbose output
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Output program version
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Output help information
.
.SH "EXIT STATUS"
\fBgit diff\-ansible\-vault\fR exits with a value of \fB0\fR if the diff is able to complete without error, and \fB1\fR if an error occurs\.
.
.SH "COPYRIGHT"
Git Diff Ansible Vault is copyright (c) 2016, Tom Marshall\. Released under the MIT license\.
.
.SH "SEE ALSO"
\fBgit\-diff\fR(1)
